data_dir: "MWI_2019_IHS-V_v06_M_Stata"

cols:
  hh_l01: purchased_item
  hh_l02: item_code
  hh_l03: item_count
  hh_l04: item_age
  hh_l05: money_that_could_be_made_by_selling_item 
  hh_l06: purchased_or_paid_for_item_in_last_year
  hh_l07: total_amount_paid_for_item_in_last_year