data_dir: "MWI_2019_IHS-V_v06_M_Stata"

cols:
  hh_f01: property_use_type
  hh_f01_1a: who_owns_property_in_household
  hh_f01_1b: who_owns_property_in_household_2
  hh_f01_1b__0: who_outside_household_owns_property
  hh_f01_1b__1: who_outside_household_owns_property_2
  hh_f01_1c: who_owns_property_in_household_3
  hh_f01_1d: who_owns_property_in_household_4
  hh_f01_1filter: anyone_else_outside_household_owns_property
  hh_f01_2: type_of_ownership_document
  hh_f01_2_oth: other_type_of_ownership_document
  hh_f01_3: able_to_provide_ownership_document
  hh_f02: amount_owner_could_receive_if_sold
  hh_f03a: amount_owner_could_receive_in_rent
  hh_f03b: rent_time_unit
  hh_f04_3: user_pays_land_rent
  hh_f04_4: total_amount_paid_in_land_rent_during_last
  hh_f04_5: have_to_pay_property_taxes
  hh_f04_6: total_amount_paid_in_property_taxes_during_last
  hh_f04a: amount_paid_to_rent_property
  hh_f04b: rent_time_unit_2
  hh_f05: age_of_dwelling
  hh_f06: type_of_construction_materials
  hh_f07: outer_walls_material
  hh_f07_oth: other_outer_walls_material
  hh_f08: type_of_roof
  hh_f08_oth: other_type_of_roof
  hh_f09: type_of_floor
  hh_f09_oth: other_type_of_floor
  hh_f10: num_rooms_occupied
  hh_f11: lighting_fuel_source
  hh_f11_oth: other_lighting_fuel_source
  hh_f12: cooking_fuel_source
  hh_f12_oth: other_cooking_fuel_source
  hh_f13: ever_use_firewood_for_fuel
  hh_f14: ever_collect_firewood
  hh_f15: where_collect_firewood
  hh_f15_oth: other_where_collect_firewood
  hh_f16a: time_taken_to_walk_from_dwelling_to_where_collect_firewood
  hh_f16b: time_unit_for_walking_to_collect_firewood
  hh_f17: of_firewood_used_how_much_collected
  hh_f18: total_value_of_firewood_used_in_past_week
  hh_f20a: in_event_of_blackout_source_of_light
  hh_f20a_oth: other_in_event_of_blackout_source_of_light
  hh_f20b: in_event_of_blackout_source_of_cooking_fuel
  hh_f20b_oth: other_in_event_of_blackout_source_of_cooking_fuel
  hh_f21: electricity_via_escom
  hh_f22: weeks_to_wait_until_connection_worked
  hh_f23: unofficial_fee_paid_for_connection
  hh_f24: frequency_of_blackouts_in_last_year
  hh_f25: amount_paid_for_electricity
  hh_f26_1: escom_is_responsive
  hh_f26_2: satisfied_with_escom
  hh_f26a: cost_of_electricity_time
  hh_f26b: cost_of_electricity_time_unit
  hh_f27: does_village_have_electricity
  hh_f29: main_reason_not_having_electricity
  hh_f29_oth: other_main_reason_not_having_electricity
  hh_f30a: amount_of_time_waited_for_electricity
  hh_f30b: time_unit_for_waiting_for_electricity
  hh_f31: is_there_a_mtl_telephone_in_unit
  hh_f32: total_cost_for_mtl_telephone_service_over_last_period
  hh_f33a: amount_of_time_telephone_cost_paid_for
  hh_f33b: time_unit_for_telephone_cost_paid_for
  hh_f34: num_working_cell_phones_in_household
  hh_f35: total_cost_for_cell_phone_service_over_last_period
  hh_f36_1: drinking_water_source
  hh_f41: type_of_toilet