col_names:
  hh_mod_g1:
    case_id: case_id
    HHID: HHID
    hh_g00_1: Who in the HH is most knowledgable about food consumption in the HH?
    hh_g00_2: Who in the household is reporting information on food consumption in this househ
    hh_g01: Item consumed in last week?
    hh_g01_oth: hh_g01_oth
    hh_g02: item_code
    hh_g03a: Quantity consumed in last week
    hh_g03b: unit_code
    hh_g03b_label: unit_code_label
    hh_g03b_oth: hh_g03b_oth
    hh_g03c: hh_g03c
    hh_g03c_1: hh_g03c_1
    hh_g04a: Quantity purchased
    hh_g04b: Quantity purchased in last week unit_code
    hh_g04b_label: Quantity purchased in last week unit_label
    hh_g04b_oth: hh_g04b_oth
    hh_g04c: hh_g04c
    hh_g04c_1: hh_g04c_1
    hh_g05: Amount paid
    hh_g06a: Own-production quantity
    hh_g06b: Own-production unit_code
    hh_g06b_label: Own-production unit_label
    hh_g06b_oth: hh_g06b_oth
    hh_g06c: hh_g06c
    hh_g06c_1: hh_g06c_1
    hh_g07a: Gifts and other sources quantity
    hh_g07b: Gifts and other sources unit_code
    hh_g07b_label: Gifts and other sources unit_label
    hh_g07b_oth: hh_g07b_oth
    hh_g07c: hh_g07c
    hh_g07c_1: hh_g07c_1

  mrk_mod_d:
    MarketID: Unique Market ID
    MarketID_Visit: Survey Solutions Unique Visit ID
    D01: item_available
    d1_a: item_name
    d1_b: item_code
    d1_c: unit_name
    d1_d: unit_code
    d1_g: item_weight_1
    d1_h: item_price_1
    d1_i: item_weight_2
    d1_j: item_price_2
    d1_k: item_weight_3
    d1_l: item_price_3
    d1_m: item_available_market
  


